##########           LIQUIBASE FLOWFILE                ##########
##########  learn more http://docs.liquibase.com/flow  ##########

globalVariables:
  ROLLBACK_TYPE: ${ROLLBACK_TYPE}
  ROLLBACK_COUNT: ${ROLLBACK_COUNT:-0}
  ROLLBACK_TAG: ${ROLLBACK_TAG:-""}
  CHANGESET_ID: ${LB_CHANGESET_ID:-""}
  CHANGESET_AUTHOR: ${LB_CHANGESET_AUTHOR:-""}
  CHANGESET_PATH: ${LB_CHANGESET_PATH:-""}
  ART_DIR: ${ART_DIR}

stages:

  Rollback-Type:
    actions:
      - type: shell
        command: |
          set +x
          echo "Rollback type: ${ROLLBACK_TYPE}"
          if [ "${ROLLBACK_TYPE}" == "rollback_count" ]; then
            echo "Rollback count: ${ROLLBACK_COUNT}"
          elif [ "${ROLLBACK_TYPE}" == "rollback_to_tag" ]; then
            echo "Rollback to tag: ${TAG}"
          elif [ "${ROLLBACK_TYPE}" == "rollback_one_changeset" ]; then
            echo "Rollback one changeset - Author: ${CHANGESET_AUTHOR}, ID: ${CHANGESET_ID}, Path: ${CHANGESET_PATH}"
          else
            echo "ERROR: Invalid rollback type '${ROLLBACK_TYPE}'. Must be one of: rollback_count, rollback_to_tag, rollback_one_changeset."
            exit 1
          fi

  History-before-Rollback:
    actions:
      - type: liquibase
        command: history
        globalArgs: { output-file: "${ART_DIR}/liquibase_history_before.log" }

  Rollback-Count:
    actions:
      - type: liquibase
        if: "${ROLLBACK_TYPE} == 'rollback_count'"
        command: rollback-count
        cmdArgs: { count: "${ROLLBACK_COUNT}" }
        globalArgs: { reports-path: "${ART_DIR}", reports-name: "rollback-count-report.html" }

  Rollback-To-Tag:
    actions:
      - type: liquibase
        if: "${ROLLBACK_TYPE} == 'rollback_to_tag'"
        command: rollback
        cmdArgs: {tag: "${ROLLBACK_TAG}"}
        globalArgs: { reports-path: "${ART_DIR}", reports-name: "rollback-to-tag-report.html" }

  Rollback-One-Changeset:
    actions:
      - type: liquibase
        if: "${ROLLBACK_TYPE} == 'rollback_one_changeset'"
        command: rollback-one-changeset
        cmdArgs: { changeset-author: "${CHANGESET_AUTHOR}", changeset-id: "${CHANGESET_ID}", changeset-path: "${CHANGESET_PATH}", force: "true" }
        globalArgs: { reports-path: "${ART_DIR}", reports-name: "rollback-one-changeset-report.html" }
  
  ## The endStage ALWAYS RUNS. 
  ## So put actions here which you desire to perform whether previous stages' actions succeed or fail.
  ## If you do not want any actions to ALWAYS RUN, simply delete the endStage from your flow file.

endStage:
  actions:
  - type: liquibase
    command: history
    globalArgs: { output-file: "${ART_DIR}/liquibase_history_after.log" }